- web/Gemfile
This is just fixing the branch to use main since the temporary branch was merged.
> Fix app gem temporary github branch

- web/.gitignore
- web/app/controllers/home_controller.rb
- web/lib/tasks/build.rake
If a developer was running `dev` after a `build` call, the app would try to load `public/index.html` instead of reaching the root endpoint, which broke everything.
Moving the symlink one level down so we're not loading it directly - that file is loaded by the root endpoint anyway, so it wouldn't break any requests to `/`.
> Move production index.html into dist folder

- README.md
- web/Gemfile
Copy/paste error from PHP README
Change `composer build` to `rake build:all`
> Change 'composer build' to 'rake build:all'

- README.md
As part of the Shopify API and app template strategy, the public repos were renamed to provide a more consistent naming convention.
Where applicable, this PR renames the following repos to match the new naming convention.
- `Shopify/shopify_api` -> `Shopify/shopify-api-ruby`
- `Shopify/shopify-node-api` -> `Shopify/shopify-api-node`
- `Shopify/shopify-php-api` -> `Shopify/shopify-api-php`
- `Shopify/shopify-app-node` -> `Shopify/shopify-app-template-node`
- `Shopify/shopify-app-php` -> `Shopify/shopify-app-template-php`
> Update API repo links (post Editions 2022 tidy-up)

- README.md
I landed on this repo from https://shopify.dev/apps/tools#app-templates and tried to create a ruby app.
It failed with the following error (see below). Adding an `=` to the `--template` flag allowed the command to run sucessfully.
```
➜  vault-pages git:(app-creation-using-spin) npm init @shopify/app@latest --template ruby
Need to install the following packages:
@shopify/create-app@latest
Ok to proceed? (y) y
━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unexpected argument: ruby
See more help with --help
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
npm ERR! code 1
npm ERR! path /Users/petar/src/github.com/Shopify/vault-pages
npm ERR! command failed
npm ERR! command sh -c create-app "ruby"
npm ERR! A complete log of this run can be found in:
npm ERR! …
```
> Fix "Installing the template" examples

- web/Gemfile
- web/app/controllers/home_controller.rb
- web/app/services/application_service.rb
- web/config/initializers/shopify_app.rb
With the addition of the `embedded` param coming from Shopify, we can optimize the processing of OAuth to avoid screen flickering (switching to full screen then back again to iFrame, etc.)
Fixes https://github.com/Shopify/first-party-library-planning/issues/393
Added `embedded_app_url` to `config` to point to `/ExitIframe`, page in FE.  Also added checking of `embedded` parameter from Shopify to determine if top-level or in an iframe.  Will redirect (via App Bridge) to load app in iFrame if top-level.
> Add processing for OAuth flicker reduction

- README.md
- web/config/initializers/shopify_app.rb
Some teams want to run CLI3 inside a spin instance. Right now this is not possible because the spin shop url domains are not supported by default. Although the users could configure their specific domain manually there will be less friction if the CLI could set that custom domain in an automatic way when the dev command is used.
For a more complete context of the problem to solve there is a [doc](https://docs.google.com/document/d/1V1lMGR5uqi2Lsy8Y1e2zj_-8cGUFjUbVOZ-2z4CuQA4/edit#)
Receive a custom store domain using environment variables and configure `config.myshopify_domain`
> Added support for custom store domains

- web/Gemfile
- web/config/environments/development.rb
Some teams want to run CLI3 inside a spin instance without using `ngrok` nor any other tunnelling solution. To achieve that an `nginx` configuration is going to be added to the partners constellation [here](https://github.com/Shopify/partners/pull/42756). Once merged, the requests to access the CLI should point to `cli.{SPIN_FQDN}`.
Right now, the template is not supporting any custom host except for `ngrok`
An external way to set a custom value for the setting `hosts` must be added
- The env variable `SHOP_CUSTOM_DOMAIN` added to support custom store domains is reused [here](https://github.com/Shopify/shopify-app-template-ruby/pull/44) for setting the `hosts`
- The value of the  `SHOP_CUSTOM_DOMAIN` env variable always contains the prefix `shopify` prepending the real domain.
- The …
> Support custom domains hosts

- .github/workflows/stale.yml
Issues that were closed by our stale workflow were getting closed as "complete". This might be confusing so we should close as `not_planned`.
[We are also doing this in `shopify_app`](https://github.com/Shopify/shopify_app/pull/1582)
> Add `not_planned reason` to Stale Workflow

- web/Gemfile
- web/config/environments/production.rb
- web/db/schema.rb
This PR simply updates the dependency for the `shopify_app` gem. The schema file update was automatic when I rebuilt the app to test, so I think we may have missed updating it before.
> Update shopify_app to 21.4.0

- Dockerfile
- web/Gemfile
Fixes https://github.com/Shopify/shopify-dev/issues/29573
There was a little bit of drift since the template was updated, and a new ruby version broke building the Docker container because a new ruby version was released.
Making the ruby version in the Gemfile a little more flexible, and ensuring the `openssl` package gets installed in the Docker container, so that the build process works normally again.
> Fix deployment issues

- web/config/routes.rb
In development mode, the frontend runs on a separate process, and proxies requests to the backend.
By default, that only happens for paths under `/api`, under the assumption that the app is a single-page application. When adding backend routes outside that path, it's important to remember that we need to add proxy exceptions too, or the FE will take over and render the react app in development.
This PR adds a comment to the routes file to help remind folks about the proxy rules.
> Add proxy instructions for non-API routes

- web/config/application.rb
Embedded apps need to set certain headers to ensure they can run in an iframe and receive requests from extensions.
This PR checks if the app is embedded and if so, sets the following headers for all responses:
- `Access-Control-Allow-Origin`
- `Access-Control-Allow-Headers`
- `Access-Control-Expose-Headers`
> chore: Add access control headers for embedded apps

- web/config/initializers/shopify_app.rb
This PR is a part of an [overall Shopify directive](https://github.com/Shopify/trust-partnerships/issues/290) to remove any privacy regulation-specific terminology from Shopify's codebase in favor of privacy language that is more generalized.
* Replaces instances of `GDPR` with `privacy`
> Rephrasing GDPR terminology in Shopify/shopify-app-template-ruby

- web/Gemfile
- web/app/controllers/products_controller.rb
- web/app/services/product_creator.rb
- web/bin/bundle
- web/bin/importmap
- web/bin/rails
- web/bin/rake
- web/bin/setup
- web/config/application.rb
- web/config/boot.rb
- web/config/environments/development.rb
- web/config/environments/production.rb
- web/config/environments/test.rb
- web/config/initializers/content_security_policy.rb
- web/config/initializers/filter_parameter_logging.rb
- web/config/initializers/permissions_policy.rb
- web/config/puma.rb
- web/db/migrate/20220609125627_create_shops.rb
- web/db/migrate/20220609125631_add_shop_access_scopes_column.rb
- web/db/schema.rb
- web/db/seeds.rb
- web/test/channels/application_cable/connection_test.rb
- web/test/test_helper.rb
We want to start new applications using the latest Rails version available.
This PR: 
- updates Rails to version 7.1 in the Gemfile
- runs  `bin/rails app:update` following the proposed process
- switch `config.load_defaults` to 7.1
- runs `rubocop -A` to have the code uniform across the project (I can also move this change to another PR if needed)
> Update Rails version to 7.1

- web/bin/bundle
- web/bin/importmap
- web/bin/rails
- web/bin/rake
- web/bin/setup
- web/db/migrate/20220609125627_create_shops.rb
- web/db/migrate/20220609125631_add_shop_access_scopes_column.rb
- web/db/schema.rb
- web/db/seeds.rb
With #133, I used the global rubocop configuration first and I changed some files that were excluded by the project-specific Rubocop rules. I re-run the right configuration later, but since those files are excluded, the changes were not reverted.
Those changes are unnecessary, and this PR is reverting the files to the previous version. 
> Revert rubocop unwanted changes

- web/config/initializers/shopify_app.rb
Related to https://github.com/Shopify/shopify-api-ruby/issues/1328
This reverts commit 82b9d7a174447098911f0a198b57fc922531578f.
The template is not set up to handle declarative webhooks config yet. It's still relying on the convention of matching webhook topic with a job class after registering with a centralized manager.
https://github.com/Shopify/shopify_app/blob/b921685a0dbf1948905cd3057d35d2f484cdbce8/lib/shopify_app/managers/webhooks_manager.rb#L53
Adds back webhook registrations for compliance topics and app/uninstalled
```
shopify app init --template=https://github.com/Shopify/shopify-app-template-ruby#sle-c/revert-declarative-webhook-config
```
Run `shopify app dev` and preview the app in your test shop
> [Fix] Revert "Add declarative webhooks and remove imperative"

- web/config/routes.rb
I had this change in this [PR](https://github.com/Shopify/shopify-app-template-ruby/pull/138), but it got lost in a merge conflict. 
This change is required to properly route webhook requests to the specific event routes
Fixes #0000 
> Update routes for declarative webhooks

- web/Gemfile
- web/test/test_helper.rb
Currently, we can't import test helpers from `shopify_app` because they require some dependencies we're missing.
Adding / loading the dependencies.
> [Chore] Fix test requires

- web/config/initializers/shopify_app.rb
Closes https://github.com/Shopify/develop-app-runtime-primitives/issues/467
This PR changes the initializer to always forward `config.old_secret` to `ShopifyAPI::Context`.
It also moves `config.old_secret` close to `config.secret` and adds link to documentation about secret rotation.
> Update `shopify_app` initializer to setup `ShopifyAPI::Context` with `old_api_secret_key`

- web/app/controllers/products_controller.rb
- web/app/services/product_counter.rb
Test with this command
```
shopify app init --template=https://github.com/Shopify/shopify-app-template-ruby#andy-liuu/Use-GraphQL-queries-in-the-Ruby-app-template-and-remove-Rest       
```
Fixes https://github.com/Shopify/first-party-library-planning/issues/691
- Converting the rest api call to a graphql call
- using the same style as the other gql call
not applicable
not applicable
> Fix: Use GraphQL queries in the Ruby app template and remove Rest

- shopify.app.toml
- web/app/controllers/webhooks/app_scopes_update_controller.rb
- web/app/jobs/app_scopes_update_job.rb
- web/config/routes.rb
Closes: https://github.com/Shopify/develop-app-runtime-primitives/issues/387
Relates to: https://github.com/Shopify/shopify-app-template-remix/pull/875
- Add new webhook subscription for `app_scopes_update`
- Add controller & job to handle `app_scopes_update` webhook to update the DB's `access_scopes` column
1. Init new app from template
```
shopify app init --template=https://github.com/Shopify/shopify-app-template-ruby#zoey/subscribe-scope-update-webhook
```
2. Create and install new app on a store
3. See a record in `shop` DB for the installed shop
4. Update `shopify.app.toml` to include different `scopes`
5. Reload the app and approve newly requested scopes
6. See the webhook request and the DB column is updated for the app.
https://screenshot.click/30-52-obkwf-t5j34.mp4
**Note**: …
> Update access scopes in DB from `app_scopes_update` webhook subscription

- package.json
I see this warning
```
warning @shopify/app@3.58.2: This package is deprecated. As of Shopify CLI version 3.59.0, it is bundled with @shopify/cli. Please use that package instead.
```
- Removes `@shopify/app` package
- Specify `@shopify/cli` version to use bundled version
> Remove shopify app package
